[project]
name = "eds_prise"
r_version = "4.5"

repositories = [
    { alias = "CRAN", url = "https://packagemanager.posit.co/cran/latest" },
]

dependencies = [
    { name = "edstr", git = "https://github.com/hebstr/edstr.git", branch = "main" },
    "tidyverse",
    "yardstick",
    "DatabaseConnector",
    "duckdb",
    "openxlsx2",
    "DBI",
    "nanoparquet",
]
